config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts do
         resources :comments, only: [:index, :create]
        end
      end
    end
  end

  root to: "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :destroy, Post, author_id: user.id
    can :destroy, Comment, user_id: user.id
    can :destroy, Post if user.role == 'admin'
    can :destroy, Comment if user.role == 'admin'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :update_comments_count

  def update_comments_count
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :update_likes_count

  def update_likes_count
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_user_posts_count

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_user_posts_count
    post_count = Post.where(author_id:).count
    author.update(posts_counter: post_count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!
  before_action :find_user
  before_action :find_post

  def index
    @comments = Comment.all
    render json: @comments
  end

  def create
    @comment = @post.comments.build(user: current_user, text: comment_params[:text])
    if @comment.save
      render json: @comment, status: :created
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def find_post
    @post = @user.posts.find(params[:post_id])
  end

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @items = Post.all
    render json: @items
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @items = User.all
    render json: @items
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :name)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user
  def create
    post_id = params[:post_id]
    user_id = params[:user_id]

    @comment = Comment.new(user_id: current_user.id, post_id:, text: comment_params[:text])

    if @comment.save
      redirect_to user_post_path(user_id:, id: post_id), notice: 'Comment created successfully.'
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])

    if @comment.destroy
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully deleted.'
    else
      redirect_to user_post_path(@user, @post), alert: 'Failed to delete comment.'
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    user_id = params[:user_id]
    post_id = params[:post_id]

    @like = Like.new(user_id:, post_id:)

    flash[:notice] = if @like.save
                       'Post liked successfully.'
                     else
                       'Unable to like the post.'
                     end
    redirect_to user_post_path(user_id:, id: post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :set_post, only: [:show]

  def index
    @posts = @user.posts.includes(:comments)
  end

  def show; end

  def create
    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to user_posts_path(params[:user_id]), notice: 'Post created successfully.'
    else
      flash[:error] = @post.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])

    if @post.destroy
      redirect_to user_posts_path(@user), notice: 'Post was successfully deleted.'
    else
      redirect_to user_post_path(@user, @post), alert: 'Failed to delete post.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = @user.posts.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def show
    @posts = @user.posts
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_with model: Comment, url: user_post_comments_path(@user), method: :post do |form| %>
  <%= form.label :text, 'Comment Text' %>
  <%= form.text_area :text %>
  <%= form.submit 'Create Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'styles' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="posts">
  <div class="user-card">
    <div class="user-photo">
        <div class= "image-contain"></div>
    </div>
      <div class="user-name">
        <h2 class="name"><%= @user.name %></h2>
        <p class="posts-counter">Number of posts: <%= @user.posts_counter %></p>
      </div>
  </div>
  <ul class="user-posts">
    <% @posts.each do |post| %>
      <li >
        <div class="user-post">         
        <%= link_to user_post_path(@user, post), class: 'no-text-decoration' do %>
          <h2 class="user-post-content"><%= post.title %></h2>
          <p class="user-post-content"><%= post.text %></p>
          <div class="comments-likes">
              <span>Comments: <%= post.comments_counter %></span> 
              <span>Likes: <%= post.likes_counter %></span>
          </div>
        <% end %>
        
        </div>
        <ul class="user-comments">
            <% post.recent_comments.each do |comment| %>
              <li>
                <p><strong><%= comment.user.name %>:</strong> <%= comment.text %></p>
              </li>
            <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
  <%= link_to new_user_post_path(@user), class: 'add-post-btn' do %>
    Create New Post
  <% end %>
  <button>Pagination</button>
</div>

app/views/posts/new.html.erb
<%= form_with model: @user.posts.build, url: user_posts_path(@user), method: :post do |form| %>
  <%= form.label :title, 'Title' %>
  <%= form.text_field :title %>

  <%= form.label :text, 'Post Content' %>
  <%= form.text_area :text %>

  <%= form.submit 'Create Post' %>
<% end %>

app/views/posts/show.html.erb
<div class="user-post-details">
  <div class="user-post-box-1">
    <div class="user-post-top">
      <p><%= @post.title %> by <%= @user.name %></p> 
      <div class="comments-likes">Comments: <%= @post.comments_counter %> Likes: <%= @post.likes_counter %> </div>
    </div>
    <p class="user-post-text">
      <%= @post.text %>
    </p>

    <%= form_with model: @like, url: user_post_likes_path(user_id: @post.author.id, post_id: @post.id), method: :post, remote: true do |form| %>
      <%= form.submit 'Like', class: 'like-button' %>
    <% end %>

    <% if can? :destroy, @post %>
      <%= form_with model: @post, url: user_post_path(@user, @post), method: :delete, remote: true do |form| %>
        <%= form.submit 'Delete', class: 'delete-button' %>
      <% end %>
    <% end %>
  </div>

  <ul class="user-post-box-2">
    <% @post.comments.each do |comment| %>
    <li>
        <p><strong><%= comment.user.name %>:</strong> <%= comment.text %></p>
        <% if can?(:destroy, comment) %>
          <%= form_with model: comment, url: user_post_comment_path(@user, @post, comment), method: :delete, remote: true do |form| %>
          <%= form.submit 'Delete comment', class: 'delete-button' %>
        <% end %>
        <% end %>
    </li>
    <% end %>
  </ul>
  <%= link_to new_user_post_comment_path(@user,@post), class: 'btn btn-primary' do %>
    Add Comment
  <% end %>
</div>

app/views/users/index.html.erb
<div class="users">
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
<% end %>
    <% @users.each do |user| %>
        <%= link_to user_path(user), class: 'no-text-decoration' do %>
        <div class="user-card">
            <div class="user-photo">
                <div class= "image-contain"></div>
            </div>
            <div class="user-name">
                <h2 class="name"><%= user.name %></h2>
                <p class="posts-counter">Number of posts: <%= user.posts_counter %></p>
            </div>
        </div>
        <% end %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="user-id">
  <div class="user-card">
    <div class="user-photo">
        <div class= "image-contain"></div>
    </div>
      <div class="user-name">
        <h2 clas="name"><%= @user.name %></h2>
        <p class="posts-counter">Number of posts: <%= @user.posts_counter %></p>
      </div>
  </div>

  <p class="user-bio"><strong>Bio:</strong> <%= @user.bio %></p>

  <ul class="user-posts">
    <% @user.recent_posts.each do |post| %>
      <%= link_to user_post_path(@user, post), class: 'no-text-decoration' do %>
      <li class="user-post">
          <h2><%= post.title %></h2>
          <p><%= post.text %></p>
          <div class="comments-likes">
            <span>Comments: <%= post.comments_counter %></span>, 
            <span>Likes: <%= post.likes_counter %></span>
          </div>
      </li>
      <% end %>
    <% end %>
  </ul>
  
  <div class="buttons">

  <%= link_to user_posts_path(@user), class:'see-all-posts-btn' do %>
  <button>
    See all posts
  </button>
  <% end %>

  </div>
</div>